# Sets are an unordered collection of unique values.
m = int(input())
set_m = set(map(int, input().split()))
n = int(input())
set_n = set(map(int, input().split()))
union_setm_setn = set_m.union(set_n)
intersect_setm_setn = set_m.intersection(set_n)
#diff_setm_setn = set_m.difference(set_n)
diff = union_setm_setn.difference(intersect_setm_setn)
# print(union_setm_setn)
# print(intersect_setm_setn)
x = sorted(diff)
print(type(x))
# print(x)
for i in x:
    print(i)